# Generated by Django 6.0 on 2025-12-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
