# Generated by Django 6.0 on 2025-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_date_added_cart_created_at_and_more'),
        ('store', '0004_alter_product_description_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
