# Generated by Django 6.0 on 2025-12-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Variation',
            new_name='variations',
        ),
    ]
